/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MinimizacionVista;

import MinimizacionControl.ControladorMin;
import java.awt.Canvas;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author rinco
 */
public class VistaMin extends javax.swing.JFrame {
    private ControladorMin controlador;
    private TextPrompt placeHolder;

    /**
     * Creates new form Vista
     */
    public VistaMin() {
        initComponents();
        controlador = new ControladorMin(this);
        mensajesDeAyuda();
    }
    
    public void mensajesDeAyuda(){
        placeHolder = new TextPrompt("Ej: q0-q1-q2-q3", txtEstados);
        placeHolder = new TextPrompt("Ej: a-b", txtAlfabeto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cmbEstadosCreacion = new javax.swing.JComboBox<>();
        cmdBorrarEstado = new javax.swing.JButton();
        cmbAlfabetoCreacion = new javax.swing.JComboBox<>();
        cmdBorrarAlfabeto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtAlfabeto = new javax.swing.JTextField();
        cmdAgregarAlfabeto = new javax.swing.JButton();
        cmdEstadoFinal = new javax.swing.JButton();
        cmdCrearAutomata = new javax.swing.JButton();
        cmdAgregarEstado = new javax.swing.JButton();
        txtEstados = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbEstFinales = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cmbEstInicial = new javax.swing.JComboBox<>();
        cmdQuitarEstFinal = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbEstTrans1 = new javax.swing.JComboBox<>();
        cmbEstTrans2 = new javax.swing.JComboBox<>();
        cmbAlfTrans = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstTransOg = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        cmdAgregarTrans = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaAlfabetoMin = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaEstadosMin = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstTransMin = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        canva = new Canva();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("CREACIÓN AUTÓMATA"));

        cmdBorrarEstado.setText("BORRAR EST.");
        cmdBorrarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarEstadoActionPerformed(evt);
            }
        });

        cmdBorrarAlfabeto.setText("BORRAR ALF.");
        cmdBorrarAlfabeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarAlfabetoActionPerformed(evt);
            }
        });

        jLabel2.setText("Alfabeto:");

        cmdAgregarAlfabeto.setText("AGREGAR");
        cmdAgregarAlfabeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAgregarAlfabetoActionPerformed(evt);
            }
        });

        cmdEstadoFinal.setText("AGREGAR EST. FINAL");
        cmdEstadoFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEstadoFinalActionPerformed(evt);
            }
        });

        cmdCrearAutomata.setText("CREAR AUTOMATA");
        cmdCrearAutomata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearAutomataActionPerformed(evt);
            }
        });

        cmdAgregarEstado.setText("AGREGAR");
        cmdAgregarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAgregarEstadoActionPerformed(evt);
            }
        });

        jLabel3.setText("Estados:");

        jLabel10.setText("Est. Finales:");

        jLabel1.setText("Est. Inicial:");

        cmdQuitarEstFinal.setText("QUITAR EST. FINAL");
        cmdQuitarEstFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdQuitarEstFinalActionPerformed(evt);
            }
        });

        jLabel12.setText("ESTADOS CREADOS:");

        jLabel13.setText("ALFABETO CREADO:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbEstFinales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdQuitarEstFinal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmdAgregarEstado))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtAlfabeto, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmdAgregarAlfabeto)))
                    .addComponent(jLabel12)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbEstadosCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdBorrarEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdEstadoFinal))
                    .addComponent(jLabel13)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbAlfabetoCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdBorrarAlfabeto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdCrearAutomata))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbEstInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cmdAgregarEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAlfabeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdAgregarAlfabeto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEstadosCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdBorrarEstado)
                    .addComponent(cmdEstadoFinal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmbEstFinales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdQuitarEstFinal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbEstInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAlfabetoCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdBorrarAlfabeto)
                    .addComponent(cmdCrearAutomata)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("TRANSICIONES"));

        jLabel4.setText("Desde el Estado1:");

        jLabel5.setText("Hacia el Estado2:");

        jLabel6.setText("Con el Simbolo:");

        jScrollPane1.setViewportView(lstTransOg);

        jButton3.setText("BORRAR TRANS.");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("MINIMIZAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        cmdAgregarTrans.setText("AGREGAR TRANS.");
        cmdAgregarTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAgregarTransActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4))
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbEstTrans1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbEstTrans2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(12, 12, 12)
                        .addComponent(cmbAlfTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdAgregarTrans)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbEstTrans1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdAgregarTrans)
                    .addComponent(cmbAlfTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbEstTrans2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("AUTÓMATA MINIMIZADO"));

        jLabel7.setText("ALFABETO:");

        txaAlfabetoMin.setColumns(20);
        txaAlfabetoMin.setRows(5);
        jScrollPane2.setViewportView(txaAlfabetoMin);

        jLabel8.setText("ESTADOS");

        txaEstadosMin.setColumns(20);
        txaEstadosMin.setRows(5);
        jScrollPane3.setViewportView(txaEstadosMin);

        jLabel9.setText("TRANSICIONES:");

        lstTransMin.setColumns(20);
        lstTransMin.setRows(5);
        jScrollPane4.setViewportView(lstTransMin);

        jLabel11.setText("GRÁFICO:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)
                                .addGap(158, 158, 158)
                                .addComponent(jLabel8)
                                .addGap(168, 168, 168))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(canva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(canva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdAgregarAlfabetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAgregarAlfabetoActionPerformed
        controlador.agregarAlfabeto();
    }//GEN-LAST:event_cmdAgregarAlfabetoActionPerformed

    private void cmdAgregarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAgregarEstadoActionPerformed
        controlador.agregarEstado();
    }//GEN-LAST:event_cmdAgregarEstadoActionPerformed

    private void cmdBorrarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarEstadoActionPerformed
        controlador.borrarEstado();
    }//GEN-LAST:event_cmdBorrarEstadoActionPerformed

    private void cmdBorrarAlfabetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarAlfabetoActionPerformed
        controlador.borrarAlfabeto();
    }//GEN-LAST:event_cmdBorrarAlfabetoActionPerformed

    private void cmdCrearAutomataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearAutomataActionPerformed
        controlador.crearAutomata();
    }//GEN-LAST:event_cmdCrearAutomataActionPerformed

    private void cmdAgregarTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAgregarTransActionPerformed
        controlador.agregarTrans();
    }//GEN-LAST:event_cmdAgregarTransActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        controlador.borrarTrans();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        controlador.minimizar();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cmdEstadoFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEstadoFinalActionPerformed
        controlador.agregarEstadoFinal();
    }//GEN-LAST:event_cmdEstadoFinalActionPerformed

    private void cmdQuitarEstFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdQuitarEstFinalActionPerformed
        controlador.quitarEstadoFinal();
    }//GEN-LAST:event_cmdQuitarEstFinalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMin().setVisible(true);
            }
        });
    }

    public Canva getCanva() {
        return (Canva) canva;
    }

    public JComboBox<String> getCmbEstFinales() {
        return cmbEstFinales;
    }

    public void setCmbEstFinales(JComboBox<String> cmbEstFinales) {
        this.cmbEstFinales = cmbEstFinales;
    }

    public JComboBox<String> getCmbAlfTrans() {
        return cmbAlfTrans;
    }

    public void setCmbAlfTrans(JComboBox<String> cmbAlfTrans) {
        this.cmbAlfTrans = cmbAlfTrans;
    }

    public JComboBox<String> getCmbEstTrans1() {
        return cmbEstTrans1;
    }

    public void setCmbEstTrans1(JComboBox<String> cmbEstTrans1) {
        this.cmbEstTrans1 = cmbEstTrans1;
    }

    public JComboBox<String> getCmbEstTrans2() {
        return cmbEstTrans2;
    }

    public void setCmbEstTrans2(JComboBox<String> cmbEstTrans2) {
        this.cmbEstTrans2 = cmbEstTrans2;
    }

    public ButtonGroup getButtonGroup2() {
        return buttonGroup2;
    }

    public void setButtonGroup2(ButtonGroup buttonGroup2) {
        this.buttonGroup2 = buttonGroup2;
    }

    public JComboBox<String> getCmbAlfabetoCreacion() {
        return cmbAlfabetoCreacion;
    }

    public void setCmbAlfabetoCreacion(JComboBox<String> cmbAlfabetoCreacion) {
        this.cmbAlfabetoCreacion = cmbAlfabetoCreacion;
    }

    public JComboBox<String> getCmbEstadosCreacion() {
        return cmbEstadosCreacion;
    }

    public void setCmbEstadosCreacion(JComboBox<String> cmbEstadosCreacion) {
        this.cmbEstadosCreacion = cmbEstadosCreacion;
    }

    public JButton getCmdAgregarAlfabeto() {
        return cmdAgregarAlfabeto;
    }

    public void setCmdAgregarAlfabeto(JButton cmdAgregarAlfabeto) {
        this.cmdAgregarAlfabeto = cmdAgregarAlfabeto;
    }

    public JButton getCmdAgregarEstado() {
        return cmdAgregarEstado;
    }

    public void setCmdAgregarEstado(JButton cmdAgregarEstado) {
        this.cmdAgregarEstado = cmdAgregarEstado;
    }

    public JButton getCmdBorrarAlfabeto() {
        return cmdBorrarAlfabeto;
    }

    public void setCmdBorrarAlfabeto(JButton cmdBorrarAlfabeto) {
        this.cmdBorrarAlfabeto = cmdBorrarAlfabeto;
    }

    public JButton getCmdBorrarEstado() {
        return cmdBorrarEstado;
    }

    public void setCmdBorrarEstado(JButton cmdBorrarEstado) {
        this.cmdBorrarEstado = cmdBorrarEstado;
    }

    public JButton getCmdEstadoFinal() {
        return cmdEstadoFinal;
    }

    public void setCmdEstadoFinal(JButton cmdEstadoFinal) {
        this.cmdEstadoFinal = cmdEstadoFinal;
    }

    public JTextArea getLstTransMin() {
        return lstTransMin;
    }

    public void setLstTransMin(JTextArea lstTransMin) {
        this.lstTransMin = lstTransMin;
    }

    public JList<String> getLstTransOg() {
        return lstTransOg;
    }

    public void setLstTransOg(JList<String> lstTransOg) {
        this.lstTransOg = lstTransOg;
    }

    public JTextArea getTxaAlfabetoMin() {
        return txaAlfabetoMin;
    }

    public void setTxaAlfabetoMin(JTextArea txaAlfabetoMin) {
        this.txaAlfabetoMin = txaAlfabetoMin;
    }

    public JTextArea getTxaEstadosMin() {
        return txaEstadosMin;
    }

    public void setTxaEstadosMin(JTextArea txaEstadosMin) {
        this.txaEstadosMin = txaEstadosMin;
    }

    public JTextField getTxtAlfabeto() {
        return txtAlfabeto;
    }

    public void setTxtAlfabeto(JTextField txtAlfabeto) {
        this.txtAlfabeto = txtAlfabeto;
    }

    public JTextField getTxtEstados() {
        return txtEstados;
    }

    public void setTxtEstados(JTextField txtEstados) {
        this.txtEstados = txtEstados;
    }

    public JComboBox<String> getCmbEstInicial() {
        return cmbEstInicial;
    }

    public void setCmbEstInicial(JComboBox<String> cmbEstInicial) {
        this.cmbEstInicial = cmbEstInicial;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private java.awt.Canvas canva;
    private javax.swing.JComboBox<String> cmbAlfTrans;
    private javax.swing.JComboBox<String> cmbAlfabetoCreacion;
    private javax.swing.JComboBox<String> cmbEstFinales;
    private javax.swing.JComboBox<String> cmbEstInicial;
    private javax.swing.JComboBox<String> cmbEstTrans1;
    private javax.swing.JComboBox<String> cmbEstTrans2;
    private javax.swing.JComboBox<String> cmbEstadosCreacion;
    private javax.swing.JButton cmdAgregarAlfabeto;
    private javax.swing.JButton cmdAgregarEstado;
    private javax.swing.JButton cmdAgregarTrans;
    private javax.swing.JButton cmdBorrarAlfabeto;
    private javax.swing.JButton cmdBorrarEstado;
    private javax.swing.JButton cmdCrearAutomata;
    private javax.swing.JButton cmdEstadoFinal;
    private javax.swing.JButton cmdQuitarEstFinal;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea lstTransMin;
    private javax.swing.JList<String> lstTransOg;
    private javax.swing.JTextArea txaAlfabetoMin;
    private javax.swing.JTextArea txaEstadosMin;
    private javax.swing.JTextField txtAlfabeto;
    private javax.swing.JTextField txtEstados;
    // End of variables declaration//GEN-END:variables
}
